### ISSUE TITLE
[问题]  请问Readme中，首页的jquery call 和 topics部分的jquery call有什么区别呢

### ISSUE THREAD

**Issue by lomizandtyd** [BruceDone/cnbeta#1]
请问是如何发现cb的topics部分的jquery call能够反复使用呢?
为什么首页的jquery 不能够使用呢？

---

你的方法太棒了，我在jquery方面完全不了解。
特别好奇，为什么首页下拉请求的Jquery Call 不能像topics部分反复使用呢？
另外是否能够模拟生成jquery callback ID呢？

**Comment by BruceDone** [comment]
其实首页也可以使用，之前想着可能是参数影响，后来才明白，这其实是一个jsonp ，一个跨域的json 请求，本质上也是可以反复call的，你可以尝试去掉：jQuery18005219338091555983_1448211396216 这一串之后的url访问：

http://www.cnbeta.com/topics/more?jsoncallback=&page=2&id=9&csrf_token=2d76f7089e98872e8addd6ddf08f545ba995e398&_=1448211433100

这样本质上就返回了一串json格式的字符串了。
